//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraceChurchKelseyvilleAwana.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Attendance
    {
        [DataType (DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd}")]
        public System.DateTime AttendanceDate { get; set; }

        public bool Attended { get; set; }

        public int StudentID { get; set; }

    
        public virtual Student Student { get; set; }
    }
}
